### ISSUE TITLE
Find out yet another way to disable password manager

### ISSUE THREAD

**Issue by JohnS42** [onlyoffice-testing-robot/onlyoffice_webdriver_wrapper#39]
https://github.com/onlyoffice-testing-robot/onlyoffice_webdriver_wrapper/blob/d0bab320d1273fce500bdf9ee72d792d46c70605/lib/onlyoffice_webdriver_wrapper/helpers/chrome_helper.rb#L24

Seems like chromedriver's options to disable pwd manager for this moment broken or updated
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015

**Comment by ShockwaveNN** [comment]
There is new 2.28 chromedriver is out by 2017-03-09 
And also should try ad `credentials_enable_service: false` to prefs like said in https://bugs.chromium.org/p/chromedriver/issues/detail?id=1015#c31
